version: "3"

services:
  web:
    build:
      context: .
    volumes:
      - ./django:/food_club/django
      - sqlite_db:/food_club/db.sqlite3
      - static_volume:/food_club/django/static_root
    command: >
      sh -c "./scripts/gunicorn_start.sh"
  nginx:
    build: 
      ./nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/static
    depends_on: 
      - web
    

volumes:
  sqlite_db:
  static_volume: