version: "3"

services:
  web:
    depends_on:
      - db
    environment:
      - DJANGO_SECRET_KEY
      - DJANGO_DB_NAME
      - DJANGO_DB_USER
      - DJANGO_DB_PASSWORD
      - DJANGO_DB_HOST
      - DJANGO_DB_PORT
    volumes:
      - static_volume:/food_club/django/static_root
      - media_volume:/food_club/django/media_root
    command: >
      sh -c "./scripts/gunicorn_start.sh"

  db:
    image: postgres:10.5-alpine
    environment:
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    # build: ./nginx
    image: nginx:1.15.12-alpine
    container_name: nginx
    ports:
      - 80:80
    volumes:
      # Django-related mounts
      - static_volume:/static
      - media_volume:/media
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
  postgres_data:
