version: "3"

services:
  web:
    build:
      context: .
    image: justaname94/food_club_web
    depends_on: 
      - db
    restart: always
    environment: 
      - DJANGO_SECRET_KEY
      - DJANGO_DB_NAME
      - DJANGO_DB_USER
      - DJANGO_DB_PASSWORD
      - DJANGO_DB_HOST
      - DJANGO_DB_PORT
    volumes:
      # - ./django:/food_club/django # Comment this line on swarm mode
      - static_volume:/food_club/django/static_root
      - media_volume:/food_club/django/media_root
    deploy:
      mode: replicated
      replicas: 1
    command: >
      sh -c "./scripts/gunicorn_start.sh"
  db:
    image: postgres:10.5-alpine
    environment: 
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data
  nginx:
    build: 
      ./nginx
    image: justaname94/food_club_nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/static
      - media_volume:/media
    depends_on: 
      - web
    deploy:
      mode: replicated
      replicas: 1
    

volumes:
  static_volume:
  media_volume:
  postgres_data: