version: "3"

services:
  web:
    build: 
      context: .
    volumes:
      - sqlite_db:/food_club/db.sqlite3
    ports:
      - 8000:8000
    command: >
      sh -c "./manage.py runserver 0.0.0.0:8000"
  
volumes:
  sqlite_db:
      